### ISSUE TITLE
Question: Does fastd implement perfect forward secrecy?

### ISSUE THREAD

**Issue by marek22k** [neocturne/fastd#35]
Hello,

I would like to know which encryption variants offers PFS in fastd?

Unfortunately I haven't found a forum or anything similar, so I'm posting my question here as an issue. If this is the wrong place for it, I'm sorry.

**Comment by marek22k** [comment]
I think I found the answer in the documentation:

> The modified algorithm FHMQV-C specified in the same document also provides Perfect Forward Secrecy (PFS), which isn’t the case for the simple FHMQV algorithm.

**Comment by neocturne** [comment]
@marek22k Right, you already found the relevant information - as fastd always uses FHMQV-C for its key exchange, it generally provides PFS. Session keys are rotated every 1 hour.
